/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n6.0-162-g07e3223dd0-20231031"
#endif /* AVUTIL_FFVERSION_H */
