/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n8.0-3-g08a81b090b-20250905"
#endif /* AVUTIL_FFVERSION_H */
