using CommandLine;

namespace HeadGestureDetector.App.Consoles {
    internal sealed class Options {
        [Value(0, MetaName = "in", Required = true, HelpText = "Input CSV filename. This CSV file should be generated by OpenFace.")]
        public string? Input { get; set; }

        [Option('o', "out", Required = true, HelpText = "Output CSV filename.")]
        public string? Output { get; set; }

        [Option('r', "framerate", Required = false, Default = 30d, HelpText = "Frame rate.")]
        public double FrameRate { get; set; }
    }
}
